### ISSUE TITLE
Extension identifier inclusion in rdapConformance

### ISSUE THREAD

**Issue by jasdips** [jasdips/rdap-geofeed#5]
In section 2.1, we say:

> An RDAP server conforming to this specification MUST include the "geofeed1" extension string in the "rdapConformance" array for the IP Network lookup and search responses, as well as in the help response.

On review, would it not be better to say this?

> An RDAP server conforming to this specification MUST include the "geofeed1" extension string in the "rdapConformance" array for any lookup or search response containing an IP Network object, as well as in the help response. 

This would help cover not only IP Network lookup and search responses but also, say, an Entity lookup response with "networks" set.

**Comment by tomhrr** [comment]
Yep, sounds good to me.
